version: "3.8"
services:
  dashboard_react_app:
    container_name: dashboard_frontend2
    build: ./
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
